
import type { Metadata } from 'next';
import { Inter, Open_Sans } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import { LiveChatButton } from '@/components/LiveChatButton';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Udreamms | USA',
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/Logo Udreamms.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${openSans.variable} font-sans`}>
        {children}
        <LiveChatButton />
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
